// <auto-generated />
using System;
using LorArchApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace LorArchApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250521050321_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LorArchApi.Models.Tb_Cidade", b =>
                {
                    b.Property<int>("IdCidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCidade"));

                    b.Property<int>("IdEstado")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("IdCidade");

                    b.ToTable("Cidades");
                });

            modelBuilder.Entity("LorArchApi.Models.Tb_Defeito", b =>
                {
                    b.Property<int>("IdDefeito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDefeito"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("IdDefeito");

                    b.ToTable("Defeitos");
                });

            modelBuilder.Entity("LorArchApi.Models.Tb_DefeitoMoto", b =>
                {
                    b.Property<int>("IdDefeitoMoto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDefeitoMoto"));

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("IdDefeito")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("IdMoto")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("IdDefeitoMoto");

                    b.ToTable("DefeitoMotos");
                });

            modelBuilder.Entity("LorArchApi.Models.Tb_Estado", b =>
                {
                    b.Property<int>("IdEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstado"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("IdEstado");

                    b.ToTable("Estados");
                });

            modelBuilder.Entity("LorArchApi.Models.Tb_HistoricoManutencao", b =>
                {
                    b.Property<int>("IdMovimentacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMovimentacao"));

                    b.Property<DateTime>("DataMovimento")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("IdMoto")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("IdSetorDestino")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("IdSetorOrigem")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("IdMovimentacao");

                    b.ToTable("HistoricoManutencoes");
                });

            modelBuilder.Entity("LorArchApi.Models.Tb_Localizacao", b =>
                {
                    b.Property<int>("IdLocalizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLocalizacao"));

                    b.Property<int>("IdMoto")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("IdSetor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Latitude")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Longitude")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("IdLocalizacao");

                    b.ToTable("Localizacoes");
                });

            modelBuilder.Entity("LorArchApi.Models.Tb_Lora", b =>
                {
                    b.Property<int>("IdLora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLora"));

                    b.Property<int>("Moto")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("NumeroLora")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("IdLora");

                    b.ToTable("Loras");
                });

            modelBuilder.Entity("LorArchApi.Models.Tb_Manutencao", b =>
                {
                    b.Property<int>("IdManutencao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdManutencao"));

                    b.Property<double>("CustoEstimado")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<DateTime>("DataManutencao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("IdMoto")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("IdManutencao");

                    b.ToTable("Manutencoes");
                });

            modelBuilder.Entity("LorArchApi.Models.Tb_Moto", b =>
                {
                    b.Property<int>("IdMoto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMoto"));

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("IdSetor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("IdMoto");

                    b.ToTable("Motos");
                });

            modelBuilder.Entity("LorArchApi.Models.Tb_Rfid", b =>
                {
                    b.Property<int>("IdRfid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRfid"));

                    b.Property<int>("IdMoto")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("NumeroRfid")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("IdRfid");

                    b.ToTable("Rfids");
                });

            modelBuilder.Entity("LorArchApi.Models.Tb_Setor", b =>
                {
                    b.Property<int>("IdSetor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSetor"));

                    b.Property<int>("IdUnidade")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("IdSetor");

                    b.ToTable("Setores");
                });

            modelBuilder.Entity("LorArchApi.Models.Tb_Unidade", b =>
                {
                    b.Property<int>("IdUnidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUnidade"));

                    b.Property<string>("IdCidade")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("IdUnidade");

                    b.ToTable("Unidades");
                });
#pragma warning restore 612, 618
        }
    }
}
