// <auto-generated />
using System;
using LorArchApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace LorArchApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LorArchApi.Models.Cidade", b =>
                {
                    b.Property<int>("IdCidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCidade"));

                    b.Property<int>("IdEstado")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("IdCidade");

                    b.ToTable("Cidades", (string)null);
                });

            modelBuilder.Entity("LorArchApi.Models.Defeito", b =>
                {
                    b.Property<int>("IdDefeito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDefeito"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("IdDefeito");

                    b.ToTable("Defeitos", (string)null);
                });

            modelBuilder.Entity("LorArchApi.Models.DefeitoMoto", b =>
                {
                    b.Property<int>("IdDefeitoMoto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDefeitoMoto"));

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("IdDefeito")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("IdMoto")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("IdDefeitoMoto");

                    b.ToTable("DefeitoMotos", (string)null);
                });

            modelBuilder.Entity("LorArchApi.Models.Estado", b =>
                {
                    b.Property<int>("IdEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstado"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("IdEstado");

                    b.ToTable("Estados", (string)null);
                });

            modelBuilder.Entity("LorArchApi.Models.HistoricoManutencao", b =>
                {
                    b.Property<int>("IdMovimentacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMovimentacao"));

                    b.Property<DateTime>("DataMovimento")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("IdMoto")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("IdSetorDestino")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("IdSetorOrigem")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("IdMovimentacao");

                    b.ToTable("HistoricoManutencoes", (string)null);
                });

            modelBuilder.Entity("LorArchApi.Models.Localizacao", b =>
                {
                    b.Property<int>("IdLocalizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLocalizacao"));

                    b.Property<int>("IdMoto")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("IdSetor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(12, 8)
                        .HasColumnType("DECIMAL(12,8)");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(12, 8)
                        .HasColumnType("DECIMAL(12,8)");

                    b.HasKey("IdLocalizacao");

                    b.ToTable("Localizacoes", (string)null);
                });

            modelBuilder.Entity("LorArchApi.Models.Lora", b =>
                {
                    b.Property<int>("IdLora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLora"));

                    b.Property<int>("Moto")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("NumeroLora")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("IdLora");

                    b.ToTable("Loras", (string)null);
                });

            modelBuilder.Entity("LorArchApi.Models.Manutencao", b =>
                {
                    b.Property<int>("IdManutencao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdManutencao"));

                    b.Property<double>("CustoEstimado")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<DateTime>("DataManutencao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("IdMoto")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("IdManutencao");

                    b.ToTable("Manutencoes", (string)null);
                });

            modelBuilder.Entity("LorArchApi.Models.Moto", b =>
                {
                    b.Property<int>("IdMoto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMoto"));

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("IdSetor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("IdMoto");

                    b.ToTable("Motos", (string)null);
                });

            modelBuilder.Entity("LorArchApi.Models.Rfid", b =>
                {
                    b.Property<int>("IdRfid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRfid"));

                    b.Property<int>("IdMoto")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("NumeroRfid")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("IdRfid");

                    b.ToTable("Rfids", (string)null);
                });

            modelBuilder.Entity("LorArchApi.Models.Setor", b =>
                {
                    b.Property<int>("IdSetor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSetor"));

                    b.Property<int>("IdUnidade")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("IdSetor");

                    b.ToTable("Setores", (string)null);
                });

            modelBuilder.Entity("LorArchApi.Models.Unidade", b =>
                {
                    b.Property<int>("IdUnidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUnidade"));

                    b.Property<int>("IdCidade")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("IdUnidade");

                    b.ToTable("Unidades", (string)null);
                });

            modelBuilder.Entity("LorArchApi.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<int>("Ativo")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<DateTime?>("UltimoLogin")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
